# Generated by Django 5.1.7 on 2025-04-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skill_specialization_project_workposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workposition',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
