# Generated by Django 5.1.7 on 2025-04-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_event_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='icon',
        ),
    ]
