# Generated by Django 5.1.7 on 2025-04-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skill_specialization_project_workposition_and_more'),
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, to='api.skill'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.ManyToManyField(blank=True, related_name='specialists', to='api.specialization'),
        ),
    ]
